#!/bin/sh

if [ -z "$1" ]; then
        SCRIPT_DIR=/mnt/sda2/var/lib/docker/aufs/nutanix
else
        SCRIPT_DIR=$1
fi

if [ -z "$2" ]; then
        SCRIPT_PARAM="install"
else
        SCRIPT_PARAM=$2
fi

if [ -d "$SCRIPT_DIR" ]; then
	for script in "$SCRIPT_DIR"/update*.sh
	do
		if [ -f "$script" ]; then
		        sh "$script" "$SCRIPT_PARAM"
		fi
	done
fi


